/*
 * Phonenumber Utils
 *
 * Copyright (c) 2015 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#include <stdlib.h>
#include <glib.h>
#include <system_settings.h>

#include "phn_common.h"
#include "phn_region_data.h"

struct phn_lang_info {
	const char *lang_str;
	phone_number_lang_e lang;
};

struct phn_match_info {
	phone_number_region_e region;
	phone_number_lang_e lang;
};

struct phn_region_info {
	const char *region_str;
	phone_number_region_e region;
};

const struct phn_match_info phn_match_info_table[] = {
	{PHONE_NUMBER_REGION_WESTERN_SAHARA, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_MOROCCO, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_MAURITANIA, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_COTE_D_IVOIRE, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_TOGO, PHONE_NUMBER_LANG_SPANISH},
	{PHONE_NUMBER_REGION_TOGO, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_BENIN, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_MAURITIUS, PHONE_NUMBER_LANG_SPANISH},
	{PHONE_NUMBER_REGION_MAURITIUS, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_CABO_VERDE, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_SAO_TOME_AND_PRINCIPE, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_CONGO, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_DEMOCRATIC_REPUBLIC_OF_THE_CONGO, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_ANGOLA, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_GUINEA_BISSAU, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_MOZAMBIQUE, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_COMOROS, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_SAINT_HELENA, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_TRISTAN_DA_CUNHA, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_GREECE, PHONE_NUMBER_LANG_GREEK},
	{PHONE_NUMBER_REGION_NETHERLANDS, PHONE_NUMBER_LANG_DUTCH},
	{PHONE_NUMBER_REGION_BELGIUM, PHONE_NUMBER_LANG_GERMAN},
	{PHONE_NUMBER_REGION_BELGIUM, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_BELGIUM, PHONE_NUMBER_LANG_DUTCH},
	{PHONE_NUMBER_REGION_FRANCE, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_SPAIN, PHONE_NUMBER_LANG_SPANISH},
	{PHONE_NUMBER_REGION_PORTUGAL, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_LUXEMBOURG, PHONE_NUMBER_LANG_GERMAN},
	{PHONE_NUMBER_REGION_LUXEMBOURG, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_ALAND_ISLANDS, PHONE_NUMBER_LANG_FINNISH},
	{PHONE_NUMBER_REGION_ALAND_ISLANDS, PHONE_NUMBER_LANG_NORTHERN_SAMI},
	{PHONE_NUMBER_REGION_FINLAND, PHONE_NUMBER_LANG_FINNISH},
	{PHONE_NUMBER_REGION_BULGARIA, PHONE_NUMBER_LANG_BULGARIAN},
	{PHONE_NUMBER_REGION_HUNGARY, PHONE_NUMBER_LANG_HUNGARIAN},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_MOLDOVA, PHONE_NUMBER_LANG_ROMANIAN},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_MOLDOVA, PHONE_NUMBER_LANG_RUSSIAN},
	{PHONE_NUMBER_REGION_ARMENIA, PHONE_NUMBER_LANG_AMHARIC},
	{PHONE_NUMBER_REGION_ARMENIA, PHONE_NUMBER_LANG_RUSSIAN},
	{PHONE_NUMBER_REGION_BELARUS, PHONE_NUMBER_LANG_BELARUSIAN},
	{PHONE_NUMBER_REGION_BELARUS, PHONE_NUMBER_LANG_RUSSIAN},
	{PHONE_NUMBER_REGION_SERBIA, PHONE_NUMBER_LANG_SERBIAN},
	{PHONE_NUMBER_REGION_ITALY, PHONE_NUMBER_LANG_ITALIAN},
	{PHONE_NUMBER_REGION_ROMANIA, PHONE_NUMBER_LANG_ROMANIAN},
	{PHONE_NUMBER_REGION_SWITZERLAND, PHONE_NUMBER_LANG_GERMAN},
	{PHONE_NUMBER_REGION_SWITZERLAND, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_SWITZERLAND, PHONE_NUMBER_LANG_ITALIAN},
	{PHONE_NUMBER_REGION_AUSTRIA, PHONE_NUMBER_LANG_GERMAN},
	{PHONE_NUMBER_REGION_SWEDEN, PHONE_NUMBER_LANG_SWEDISH},
	{PHONE_NUMBER_REGION_POLAND, PHONE_NUMBER_LANG_POLISH},
	{PHONE_NUMBER_REGION_GERMANY, PHONE_NUMBER_LANG_GERMAN},
	{PHONE_NUMBER_REGION_BRAZIL, PHONE_NUMBER_LANG_PORTUGUESE},
	{PHONE_NUMBER_REGION_CHILE, PHONE_NUMBER_LANG_SPANISH},
	{PHONE_NUMBER_REGION_COLOMBIA, PHONE_NUMBER_LANG_SPANISH},
	{PHONE_NUMBER_REGION_VENEZUELA, PHONE_NUMBER_LANG_SPANISH},
	{PHONE_NUMBER_REGION_INDONESIA, PHONE_NUMBER_LANG_INDONESIAN},
	{PHONE_NUMBER_REGION_THAILAND, PHONE_NUMBER_LANG_THAI},
	{PHONE_NUMBER_REGION_KAZAKHSTAN, PHONE_NUMBER_LANG_RUSSIAN},
	{PHONE_NUMBER_REGION_RUSSIAN_FEDERATION, PHONE_NUMBER_LANG_RUSSIAN},
	{PHONE_NUMBER_REGION_JAPAN, PHONE_NUMBER_LANG_JAPANESE},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA, PHONE_NUMBER_LANG_ARABIC},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA, PHONE_NUMBER_LANG_CZECH},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA, PHONE_NUMBER_LANG_FRENCH},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA, PHONE_NUMBER_LANG_KOREAN},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA, PHONE_NUMBER_LANG_CHINESE},
	{PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA, PHONE_NUMBER_LANG_CHINESE_TRADITIONAL},
	{PHONE_NUMBER_REGION_VIET_NAM, PHONE_NUMBER_LANG_VIETNAMESE},
	{PHONE_NUMBER_REGION_CHINA, PHONE_NUMBER_LANG_CHINESE},
	{PHONE_NUMBER_REGION_CHINA, PHONE_NUMBER_LANG_CHINESE_TRADITIONAL},
	{PHONE_NUMBER_REGION_TAIWAN_PROVINCE_OF_CHINA, PHONE_NUMBER_LANG_CHINESE},
	{PHONE_NUMBER_REGION_TAIWAN_PROVINCE_OF_CHINA, PHONE_NUMBER_LANG_CHINESE_TRADITIONAL},
	{PHONE_NUMBER_REGION_TURKEY, PHONE_NUMBER_LANG_TURKISH},
	{PHONE_NUMBER_REGION_SAUDI_ARABIA, PHONE_NUMBER_LANG_ARABIC},
	{PHONE_NUMBER_REGION_ISLAMIC_REPUBLIC_OF_IRAN, PHONE_NUMBER_LANG_PERSIAN},
	{PHONE_NUMBER_REGION_SYSTEM, PHONE_NUMBER_LANG_SYSTEM},
};

const struct phn_lang_info phn_lang_info_table[] = {
	{"am", PHONE_NUMBER_LANG_AMHARIC},
	{"ar", PHONE_NUMBER_LANG_ARABIC},
	{"be", PHONE_NUMBER_LANG_BELARUSIAN},
	{"bg", PHONE_NUMBER_LANG_BULGARIAN},
	{"zh", PHONE_NUMBER_LANG_CHINESE},
	{"zh_Hant", PHONE_NUMBER_LANG_CHINESE_TRADITIONAL},
	{"cs", PHONE_NUMBER_LANG_CZECH},
	{"nl", PHONE_NUMBER_LANG_DUTCH},
	{"en", PHONE_NUMBER_LANG_ENGLISH},
	{"fi", PHONE_NUMBER_LANG_FINNISH},
	{"fr", PHONE_NUMBER_LANG_FRENCH},
	{"de", PHONE_NUMBER_LANG_GERMAN},
	{"el", PHONE_NUMBER_LANG_GREEK},
	{"hu", PHONE_NUMBER_LANG_HUNGARIAN},
	{"id", PHONE_NUMBER_LANG_INDONESIAN},
	{"it", PHONE_NUMBER_LANG_ITALIAN},
	{"ja", PHONE_NUMBER_LANG_JAPANESE},
	{"ko", PHONE_NUMBER_LANG_KOREAN},
	{"se", PHONE_NUMBER_LANG_NORTHERN_SAMI},
	{"fa", PHONE_NUMBER_LANG_PERSIAN},
	{"pl", PHONE_NUMBER_LANG_POLISH},
	{"pt", PHONE_NUMBER_LANG_PORTUGUESE},
	{"ro", PHONE_NUMBER_LANG_ROMANIAN},
	{"ru", PHONE_NUMBER_LANG_RUSSIAN},
	{"sr", PHONE_NUMBER_LANG_SERBIAN},
	{"se", PHONE_NUMBER_LANG_SPANISH},
	{"sv", PHONE_NUMBER_LANG_SWEDISH},
	{"th", PHONE_NUMBER_LANG_THAI},
	{"tr", PHONE_NUMBER_LANG_TURKISH},
	{"vi", PHONE_NUMBER_LANG_VIETNAMESE},
};

const struct phn_region_info phn_region_info_table[] = {
	{"AX", PHONE_NUMBER_REGION_ALAND_ISLANDS},
	{"AL", PHONE_NUMBER_REGION_ALBANIA},
	{"DZ", PHONE_NUMBER_REGION_ALGERIA},
	{"AS", PHONE_NUMBER_REGION_AMERICAN_SAMOA},
	{"AO", PHONE_NUMBER_REGION_ANGOLA},
	{"AI", PHONE_NUMBER_REGION_ANGUILLA},
	{"AR", PHONE_NUMBER_REGION_ARGENTINA},
	{"AM", PHONE_NUMBER_REGION_ARMENIA},
	{"AC", PHONE_NUMBER_REGION_ASCENSION_ISLAND},
	{"AG", PHONE_NUMBER_REGION_ATIGUA_AND_BARBUDA},
	{"AT", PHONE_NUMBER_REGION_AUSTRIA},
	{"BS", PHONE_NUMBER_REGION_BAHAMAS},
	{"BB", PHONE_NUMBER_REGION_BARBADOS},
	{"BY", PHONE_NUMBER_REGION_BELARUS},
	{"BE", PHONE_NUMBER_REGION_BELGIUM},
	{"BJ", PHONE_NUMBER_REGION_BENIN},
	{"BM", PHONE_NUMBER_REGION_BERMUDA},
	{"BQ", PHONE_NUMBER_REGION_BONAIRE_SINT_EUSTATIUS_AND_SABA},
	{"BW", PHONE_NUMBER_REGION_BOTSWANA},
	{"BR", PHONE_NUMBER_REGION_BRAZIL},
	{"BG", PHONE_NUMBER_REGION_BULGARIA},
	{"BF", PHONE_NUMBER_REGION_BURKINA_FASO},
	{"BI", PHONE_NUMBER_REGION_BURUNDI},
	{"CV", PHONE_NUMBER_REGION_CABO_VERDE},
	{"CM", PHONE_NUMBER_REGION_CAMEROON},
	{"CA", PHONE_NUMBER_REGION_CANADA},
	{"KY", PHONE_NUMBER_REGION_CAYMAN_ISLAND},
	{"CL", PHONE_NUMBER_REGION_CHILE},
	{"CN", PHONE_NUMBER_REGION_CHINA},
	{"CO", PHONE_NUMBER_REGION_COLOMBIA},
	{"KM", PHONE_NUMBER_REGION_COMOROS},
	{"CG", PHONE_NUMBER_REGION_CONGO},
	{"CI", PHONE_NUMBER_REGION_COTE_D_IVOIRE},
	{"CU", PHONE_NUMBER_REGION_CUBA},
	{"CW", PHONE_NUMBER_REGION_CURACAO},
	{"CZ", PHONE_NUMBER_REGION_CZECH_REPUBLIC},
	{"CD", PHONE_NUMBER_REGION_DEMOCRATIC_REPUBLIC_OF_THE_CONGO},
	{"DM", PHONE_NUMBER_REGION_DOMINICA},
	{"EG", PHONE_NUMBER_REGION_EGYPT},
	{"EE", PHONE_NUMBER_REGION_ESTONIA},
	{"ET", PHONE_NUMBER_REGION_ETHIOPIA},
	{"FI", PHONE_NUMBER_REGION_FINLAND},
	{"FR", PHONE_NUMBER_REGION_FRANCE},
	{"GA", PHONE_NUMBER_REGION_GABON},
	{"GM", PHONE_NUMBER_REGION_GAMBIA},
	{"DE", PHONE_NUMBER_REGION_GERMANY},
	{"GH", PHONE_NUMBER_REGION_GHANA},
	{"GR", PHONE_NUMBER_REGION_GREECE},
	{"GL", PHONE_NUMBER_REGION_GREENLAND},
	{"GD", PHONE_NUMBER_REGION_GRENADA},
	{"GU", PHONE_NUMBER_REGION_GUAM},
	{"GG", PHONE_NUMBER_REGION_GUERNSEY},
	{"GN", PHONE_NUMBER_REGION_GUINEA},
	{"GW", PHONE_NUMBER_REGION_GUINEA_BISSAU},
	{"HU", PHONE_NUMBER_REGION_HUNGARY},
	{"IS", PHONE_NUMBER_REGION_ICELAND},
	{"IN", PHONE_NUMBER_REGION_INDIA},
	{"ID", PHONE_NUMBER_REGION_INDONESIA},
	{"IE", PHONE_NUMBER_REGION_IRELAND},
	{"IR", PHONE_NUMBER_REGION_ISLAMIC_REPUBLIC_OF_IRAN},
	{"IM", PHONE_NUMBER_REGION_ISLE_OF_MAN},
	{"IT", PHONE_NUMBER_REGION_ITALY},
	{"JM", PHONE_NUMBER_REGION_JAMAICA},
	{"JP", PHONE_NUMBER_REGION_JAPAN},
	{"JE", PHONE_NUMBER_REGION_JERSEY},
	{"JO", PHONE_NUMBER_REGION_JORDAN},
	{"KZ", PHONE_NUMBER_REGION_KAZAKHSTAN},
	{"KE", PHONE_NUMBER_REGION_KENYA},
	{"KI", PHONE_NUMBER_REGION_KIRIBATI},
	{"LV", PHONE_NUMBER_REGION_LATVIA},
	{"LS", PHONE_NUMBER_REGION_LESOTHO},
	{"LT", PHONE_NUMBER_REGION_LITHUANIA },
	{"LU", PHONE_NUMBER_REGION_LUXEMBOURG},
	{"MG", PHONE_NUMBER_REGION_MADAGASCAR},
	{"MR", PHONE_NUMBER_REGION_MAURITANIA},
	{"MU", PHONE_NUMBER_REGION_MAURITIUS },
	{"DO", PHONE_NUMBER_REGION_DOMINICAN_REPUBLIC },
	{"MS", PHONE_NUMBER_REGION_MONTSERRAT},
	{"MA", PHONE_NUMBER_REGION_MOROCCO},
	{"MZ", PHONE_NUMBER_REGION_MOZAMBIQUE},
	{"NA", PHONE_NUMBER_REGION_NAMIBIA},
	{"NL", PHONE_NUMBER_REGION_NETHERLANDS},
	{"NG", PHONE_NUMBER_REGION_NIGERIA},
	{"MP", PHONE_NUMBER_REGION_NORTHERN_MARIANA_ISLANDS},
	{"NO", PHONE_NUMBER_REGION_NORWAY},
	{"PE", PHONE_NUMBER_REGION_PERU},
	{"PL", PHONE_NUMBER_REGION_POLAND},
	{"PT", PHONE_NUMBER_REGION_PORTUGAL},
	{"PR", PHONE_NUMBER_REGION_PUERTO_RICO},
	{"KR", PHONE_NUMBER_REGION_REPUBLIC_OF_KOREA},
	{"MD", PHONE_NUMBER_REGION_REPUBLIC_OF_MOLDOVA},
	{"RO", PHONE_NUMBER_REGION_ROMANIA},
	{"RU", PHONE_NUMBER_REGION_RUSSIAN_FEDERATION},
	{"SH", PHONE_NUMBER_REGION_SAINT_HELENA},
	{"KN", PHONE_NUMBER_REGION_SAINT_KITTS_AND_NEVIS},
	{"LC", PHONE_NUMBER_REGION_SAINT_LUCIA},
	{"VC", PHONE_NUMBER_REGION_SAINT_VINCENT_AND_THE_GRENADINES},
	{"ST", PHONE_NUMBER_REGION_SAO_TOME_AND_PRINCIPE},
	{"SA", PHONE_NUMBER_REGION_SAUDI_ARABIA},
	{"SN", PHONE_NUMBER_REGION_SENEGAL},
	{"RS", PHONE_NUMBER_REGION_SERBIA},
	{"SL", PHONE_NUMBER_REGION_SIERRA_LEONE},
	{"SX", PHONE_NUMBER_REGION_SINT_MAARTEN},
	{"SK", PHONE_NUMBER_REGION_SLOVAKIA},
	{"SO", PHONE_NUMBER_REGION_SOMALIA},
	{"ZA", PHONE_NUMBER_REGION_SOUTH_AFRICA},
	{"ES", PHONE_NUMBER_REGION_SPAIN},
	{"LK", PHONE_NUMBER_REGION_SRI_LANKA},
	{"SD", PHONE_NUMBER_REGION_SUDAN},
	{"SJ", PHONE_NUMBER_REGION_SVALBARD_AND_JAN_MAYEN},
	{"SZ", PHONE_NUMBER_REGION_SWAZILAND},
	{"SE", PHONE_NUMBER_REGION_SWEDEN},
	{"CH", PHONE_NUMBER_REGION_SWITZERLAND},
	{"TW", PHONE_NUMBER_REGION_TAIWAN_PROVINCE_OF_CHINA},
	{"TH", PHONE_NUMBER_REGION_THAILAND},
	{"MK", PHONE_NUMBER_REGION_THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA},
	{"TG", PHONE_NUMBER_REGION_TOGO},
	{"TT", PHONE_NUMBER_REGION_TRINIDAD_AND_TOBAGO},
	{"TA", PHONE_NUMBER_REGION_TRISTAN_DA_CUNHA},
	{"TN", PHONE_NUMBER_REGION_TUNISIA},
	{"TR", PHONE_NUMBER_REGION_TURKEY},
	{"TC", PHONE_NUMBER_REGION_TURKS_AND_CAICOS_ISLANDS},
	{"UG", PHONE_NUMBER_REGION_UGANDA},
	{"GB", PHONE_NUMBER_REGION_UNITED_KINGDOM},
	{"US", PHONE_NUMBER_REGION_UNITED_STATES_OF_AMERICA},
	{"VE", PHONE_NUMBER_REGION_VENEZUELA},
	{"VN", PHONE_NUMBER_REGION_VIET_NAM},
	{"VG", PHONE_NUMBER_REGION_VIRGIN_ISLAND_BRITISH},
	{"VI", PHONE_NUMBER_REGION_VIRGIN_ISLAND_US},
	{"EH", PHONE_NUMBER_REGION_WESTERN_SAHARA},
	{"ZM", PHONE_NUMBER_REGION_ZAMBIA},
	{"ZW", PHONE_NUMBER_REGION_ZIMBABWE},
};

int phn_region_data_get_region_str(phone_number_region_e region, char **region_str)
{
	int ret, i;

	if (PHONE_NUMBER_REGION_SYSTEM == region) {
		char *str = NULL;
		ret = system_settings_get_value_string(SYSTEM_SETTINGS_KEY_LOCALE_COUNTRY, &str);
		if (str)
			*region_str = g_strdup(strchr(str, '_') + 1);
		free(str);
		if (SYSTEM_SETTINGS_ERROR_NONE != ret) {
			ERR("system_settings_get_value_string() Fail(%d)", ret);
			return PHONE_NUMBER_ERROR_NOT_SUPPORTED;
		}
		return PHONE_NUMBER_ERROR_NONE;
	}

	for (i = 0; i < sizeof(phn_region_info_table) / sizeof(struct phn_region_info); i++) {
		if (phn_region_info_table[i].region == region) {
			*region_str = g_strdup(phn_region_info_table[i].region_str);
			return PHONE_NUMBER_ERROR_NONE;
		}
	}
	return PHONE_NUMBER_ERROR_NOT_SUPPORTED;
}

int phn_region_data_get_lang_str(phone_number_lang_e lang, char **lang_str)
{
	int ret, i;

	if (PHONE_NUMBER_LANG_SYSTEM == lang) {
		char *str = NULL;
		ret = system_settings_get_value_string(SYSTEM_SETTINGS_KEY_LOCALE_LANGUAGE, &str);
		if (str)
			*lang_str = g_strdup(strtok(str, "_"));
		free(str);
		if (SYSTEM_SETTINGS_ERROR_NONE != ret) {
			ERR("system_settings_get_value_string() Fail(%d)", ret);
			return PHONE_NUMBER_ERROR_NOT_SUPPORTED;
		}
		return PHONE_NUMBER_ERROR_NONE;
	}

	for (i = 0; i < sizeof(phn_lang_info_table) / sizeof(struct phn_lang_info); i++) {
		if (phn_lang_info_table[i].lang == lang) {
			*lang_str = g_strdup(phn_lang_info_table[i].lang_str);
			return PHONE_NUMBER_ERROR_NONE;
		}
	}
	return PHONE_NUMBER_ERROR_NOT_SUPPORTED;
}

bool phn_region_data_find_match_info(phone_number_region_e region,
		phone_number_lang_e lang)
{
	int i;
	for (i = 0; i < sizeof(phn_match_info_table) / sizeof(struct phn_match_info); i++) {
		if (phn_match_info_table[i].region == region
				&& phn_match_info_table[i].lang == lang) {
			return true;
		}
	}
	return false;
}

